package DelhipmNew::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'DelhipmNew::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:delhipm:localhost',
        user => 'root',
        password => '',
        AutoCommit => q{1},
    }
);

=head1 NAME

DelhipmNew::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<DelhipmNew>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Cart::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

user

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
